twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        STRIPE_KEY_API_PUBLIC: '%env(STRIPE_KEY_API_PUBLIC)%'


when@test:
    twig:
        strict_variables: true
